### ISSUE TITLE
Second execution crashes the REPL

### ISSUE THREAD

**Issue by JoshOrndorff** [glenbraun/JsonPi#3]
Several of the commands (like `:run` etc) crash the REPL for me. I built the REPL according to the instructions in the README, and run on debian 9.

Always working:
`:h`, `:help`,

Always broken:
`:q`, `:quit`, `:reset`

Complicated:
`:m`, `:multi`, `:s`, `:step`, `:r`, and `:run` will all execute fine the first time I issue them. But if I issue them a second time, or issue a second one of them, the REPL crashes.

`:l`, and `:list` seem to be straight-up intermittent

The trace (for `:q`) is:
```
Run> :q

Unhandled Exception:
System.Exception: parse error
  at Microsoft.FSharp.Text.Parsing.Implementation.popStackUntilErrorShifted@278[tok,a] (Microsoft.FSharp.Text.Parsing.Tables`1[tok] tables, Microsoft.FSharp.Text.Lexing.LexBuffer`1[char] lexbuf, Microsoft.FSharp.Text.Parsing.Stack`1[a] stateStack, Microsoft.FSharp.Text.Parsing.Stack`1[a] valueStack, Microsoft.FSharp.Text.Parsing.Implementation+AssocTable actionTable, Microsoft.FSharp.Core.FSharpOption`1[T] tokenOpt) [0x000b3] in <5ae39741b0dad8caa74503834197e35a>:0 
  at Microsoft.FSharp.Text.Parsing.Implementation.interpret[tok,a] (Microsoft.FSharp.Text.Parsing.Tables`1[tok] tables, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] lexer, Microsoft.FSharp.Text.Lexing.LexBuffer`1[char] lexbuf, System.Int32 initialState) [0x00538] in <5ae39741b0dad8caa74503834197e35a>:0 
  at JsonPiRepl.main (System.String[] argv) [0x0001b] in <5ae3991ac91cf2afa74503831a99e35a>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: parse error
  at Microsoft.FSharp.Text.Parsing.Implementation.popStackUntilErrorShifted@278[tok,a] (Microsoft.FSharp.Text.Parsing.Tables`1[tok] tables, Microsoft.FSharp.Text.Lexing.LexBuffer`1[char] lexbuf, Microsoft.FSharp.Text.Parsing.Stack`1[a] stateStack, Microsoft.FSharp.Text.Parsing.Stack`1[a] valueStack, Microsoft.FSharp.Text.Parsing.Implementation+AssocTable actionTable, Microsoft.FSharp.Core.FSharpOption`1[T] tokenOpt) [0x000b3] in <5ae39741b0dad8caa74503834197e35a>:0 
  at Microsoft.FSharp.Text.Parsing.Implementation.interpret[tok,a] (Microsoft.FSharp.Text.Parsing.Tables`1[tok] tables, Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] lexer, Microsoft.FSharp.Text.Lexing.LexBuffer`1[char] lexbuf, System.Int32 initialState) [0x00538] in <5ae39741b0dad8caa74503834197e35a>:0 
  at JsonPiRepl.main (System.String[] argv) [0x0001b] in <5ae3991ac91cf2afa74503831a99e35a>:0 
```

**Comment by glenbraun** [comment]
Thanks for reporting the issue. 

Are you ever entering multiline mode? 

In multiline mode, all lines are interpreted as pi calc syntax and so will cause a syntax error. This would explain the intermittent behavior. The interpretation of commands in multiline mode needs some work. I'll look into that.

There's also the issue, it appears, that exceptions are not being captured when running on linux, which adds to the issue here.

**Comment by glenbraun** [comment]
I've made a change to the REPL command handling code. If my assumption that the issue has to do with commands in multiline mode, then I think this change should address the issue.

The issue with parser exceptions not being caught, causing the program to exit, when running on linux, is not addressed in this change.

**Comment by JoshOrndorff** [comment]
I've experimented further with this, and discovered that my initial description was not quite right. The bad news is that the changes in 4f4f3bebb772d1bab2dbd7e530c8da4042cd6cae did not fix the issue. The good news is that the correct description is much simpler than I had initially listed.

It turns out that the first command I enter (whatever it is) works as expected. But the second command I enter (whatever it is) causes the crash.

**Comment by JoshOrndorff** [comment]
Actually, it doesn't just have to be commands. Whenever I enter a second thing at the prompt the crash occurs. Here are some examples:

Two commands
```
Run> :reset
Run> :h

Unhandled Exception:
```

Two pieces of valid syntax
```
Run> world<hello>; | world(message);
Run> world<hello>; | world(message);

Unhandled Exception:
```

Two pieces of invalid syntax
```
Run> svad
Exception: parse error
Run> f

Unhandled Exception:
```

Invalid syntax then command:
```
Run> dqwe
Exception: parse error
Run> world<hello>; | world{message);

Unhandled Exception:
```

Can anyone reproduce this issue? Are there other configurations I should try?

**Comment by glenbraun** [comment]
I'm sorry but I've not been able to get anything to run on Ubuntu 16.04 so I've not been able to reproduce the issue.

I installed .net core with the instructions here: 
https://www.microsoft.com/net/learn/get-started/linux/ubuntu16-04

This wasn't enough so I tried installing fsharp from the instructions at http://fsharp.org/use/linux/
    sudu apt-get update
    sudo apt-get install fsharp

With this I was able to compile the source (using fsharpc rather than fsc). But when running dotnet JsonPiREPL.exe I get an error that FSharp.Core version 4.3.4 is missing in path lib/netstandard1.6/FSharp.Core.dll

So far I've not been able to work past this. I think the runtime might have something to do with this issue since I don't reproduce these errors on Windows. I think I'll try to create a standalone exe for .net core from windows next.

**Comment by glenbraun** [comment]
ok, I've not yet reproduced the exact same issue but I have found that building a self contained exe for .net core with Win10 as the target that the REPL doesn't work other than getting to a Run> command. The help command works but not much else. Not sure if these are close to the same results or not that you're getting on Linux. I'm trying a self contained exe for Linux now.

**Comment by glenbraun** [comment]
I was able to reproduce the issue when running in Linux. I'm not sure the reason but the command parser I was using failed on Linux vs. in Windows. I replaced the command processor with something much simpler and it seems to work fine in both Windows and Linux now.

**Comment by JoshOrndorff** [comment]
Nice work Glen,

I confirm the issue is solved for me (and even works with the mono libraries instead of official dotnetcore).

Thanks for all your work!
